Vagrant.configure("2") do |config|

  config.vm.define "gitlab" do |gitlab|
    gitlab.vm.box = "bento/centos-7.5"
    gitlab.vm.network "private_network", ip: "192.168.56.101"
    gitlab.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "4096"
    end
    gitlab.vm.provision "shell", inline: <<-SHELL
      # install updates
      sudo yum update -y
      sudo yum upgrade -y
      sudo hostnamectl set-hostname gitlab-ce.unixcloudfusion.in
      # install gitlab-ce dependencies
      sudo yum install -y curl policycoreutils openssh-server openssh-clients
      sudo systemctl enable sshd 
      sudo systemctl start sshd 
      sudo yum install postfix 
      sudo systemctl enable postfix 
      sudo systemctl start postfix 
      # let network connection settle
      sleep 5
      # Install & configure GitLab CE
      curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh | sudo bash 
      sudo yum install -y gitlab-ce
      sudo sed -i -e s/gitlab.example.com/gitlab-ce.unixcloudfusion.in/g /etc/gitlab/gitlab.rb
      sudo gitlab-ctl reconfigure
      # Install Docker CE needed for docker runner
      sudo yum install -y yum-utils device-mapper-persistent-data lvm2
      sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      sudo yum makecache fast
      sudo yum -y install docker-ce
      sudo systemctl start docker
    SHELL
  end
    
  config.vm.define "runner" do |runner|
    runner.vm.box = "ubuntu/xenial64"
    runner.vm.network "private_network", ip: "192.168.56.102"
    runner.vm.synced_folder "./data", "/home/vagrant/data"
    runner.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
    end
    runner.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y docker.io docker-compose
    docker-compose -f /home/vagrant/data/docker-compose.yml up -d runner
    # Commande for register gitlab-runner
    # docker exec -it runner gitlab-runner register
    SHELL
  end

  config.vm.define "prod" do |prod|
    prod.vm.box = "ubuntu/xenial64"
    prod.vm.network "private_network", ip: "192.168.56.103"
    prod.vm.synced_folder "./data", "/home/vagrant/data"
    prod.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
    end
    prod.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y docker.io docker-compose
    docker-compose -f /home/vagrant/data/docker-compose.yml up -d nginx-proxy
    docker-compose -f /home/vagrant/data/docker-compose.yml up -d ssl-generator
    useradd -m deployer
    usermod -aG docker deployer
    mkdir /home/deployer/.ssh
    cat /home/vagrant/data/deploy_rsa_key >> /home/deployer/.ssh/deploy_rsa_key
    cat /home/vagrant/data/deploy_rsa_key.pub >> /home/deployer/.ssh/deploy_rsa_key.pub
    cat /home/vagrant/data/deploy_rsa_key.pub >> /home/deployer/.ssh/authorized_keys
    SHELL
  end

end
